export const UPDATE_TIRECODE_AVL = 'UPDATE_TIRECODE_AVL'
export const UPDATE_SPEC_AVL = 'UPDATE_SPEC_AVL'
export const UPDATE_SPEC_VER_MATCH = 'UPDATE_SPEC_VER_MATCH'
export const EDC_1ST_TIRE = 'EDC_1ST_TIRE'
