export const TIRECODE_READING_REQUEST = 'TIRECODE_READING_REQUEST'
export const TIRECODE_READING_SUCCESS = 'TIRECODE_READING_SUCCESS'
export const TIRECODE_READING_FAIL = 'TIRECODE_READING_SUCCESS'
export const RESET_TIRE_DETAIL = 'RESET_TIRE_DETAIL'
