export const SCALE_READING_REQUEST = 'SCALE_READING_REQUEST'
export const SCALE_READING_SUCCESS = 'SCALE_READING_SUCCESS'
export const SCALE_READING_FAIL = 'SCALE_READING_FAIL'
export const SCALE_OVERRIDE = 'SCALE_OVERRIDE'
