export const SPEC_READING_REQUEST = 'SPEC_READING_REQUEST'
export const SPEC_READING_SUCCESS = 'SPEC_READING_SUCCESS'
export const SPEC_READING_FAIL = 'SPEC_READING_FAIL'
export const RESET_SPEC = 'RESET_SPEC'
