export const MOVING_AVERAGE_ARRAY_LENGTH = 5
export const DIFFERENCE_SMALL_TIRES = 5
export const DIFFERENCE_MIDIAM_TIRES = 5
export const DIFFERENCE_LARGE_TIRES = 5

export const STABILITY_WAITING = 3
export const TIMER_INTERVAL = 100
